---
title: "Clasificacion"
author: "Jose Alejandro Rojas Castro"
date: "2025-09-11"
output: html_document
---

```{r}
df <- read.csv("DATA_final.csv")
head(df)

df_CE   <- df %>% filter(LOCATION == "CE") %>% filter(Hour >= 6)
df_NTE2 <- df %>% filter(LOCATION == "NTE2") %>% filter(Hour >= 6)
df_NE   <- df %>% filter(LOCATION == "NE") %>% filter(Hour >= 6)

NE=df_NE[, c("O3","CO","NOX","PM10","PM2.5","PRS","RAINF","RH","SO2","SR","TOUT")]
CE=df_CE[, c("O3","CO","NOX","PM10","PM2.5","PRS","RAINF","RH","SO2","SR","TOUT")]
NTE2=df_NTE2[, c("O3","CO","NOX","PM10","PM2.5","PRS","RAINF","RH","SO2","SR","TOUT")]
```

```{r}
library(dplyr)

CE <- CE %>%
  mutate(O3_categoria = case_when(
    O3 <= 58 ~ "Excelente",
    O3 > 58 & O3 <= 90 ~ "Aceptable",
    O3 > 90 ~ "Malo"
  ))

CE %>%
  group_by(O3_categoria) %>%
  summarise(Conteo = n())


```

```{r}
library(ggplot2)

ggplot(CE, aes(x = O3_categoria)) +
  geom_bar(fill = c("green", "goldenrod1", "red")) +
  labs(title = "Distribución de O3 por categoría",
       x = "Categoría O3",
       y = "Conteo") +
  theme_minimal()

CE %>%
  group_by(O3_categoria) %>%
  summarise(Conteo = n()) %>%
  mutate(Porcentaje = round(Conteo / sum(Conteo) * 100, 2))



```

```{r}
library(dplyr)
library(caret)
library(nnet)  # Para regresión logística multinomial

# Convertir la variable objetivo en factor ordenado
CE$O3_categoria <- factor(CE$O3_categoria,
                          levels = c("Excelente", "Aceptable", "Malo"),
                          ordered = TRUE)

# Separar datos en entrenamiento (80%) y prueba (20%)
set.seed(123)
train_index <- createDataPartition(CE$O3_categoria, p = 0.8, list = FALSE)
train_data <- CE[train_index, ]
test_data  <- CE[-train_index, ]

```

```{r}
modelo_log <- multinom(O3_categoria ~ ., data = train_data)

```

```{r}
summary(modelo_log)

```
```{r}
predicciones <- predict(modelo_log, newdata = test_data)
# Matriz de confusión
confusionMatrix(predicciones, test_data$O3_categoria)

```

